/*Final Project
 GoogleMaps1.java
 Shashank G Hebbale(800773977)
 Sahana K Raj(800774871)
 */
package com.example.apg;

import java.text.DecimalFormat;
import java.util.ArrayList;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.util.Log;
import android.view.Menu;
import android.widget.ListView;

import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.GoogleMap.OnInfoWindowClickListener;
import com.google.android.gms.maps.MapFragment;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.Marker;
import com.google.android.gms.maps.model.MarkerOptions;

@SuppressLint("NewApi")
public class GoogleMaps1 extends Activity {
	
	 GPStracker gps;
	 GoogleMap mMap;ListView listview;
	 String finalAddress;
	 double latitude,longitude;
	 Activity act;
	 static Handler handler1;
	 static Handler handl;
	 String url;
   @Override
   protected void onCreate(Bundle savedInstanceState) {
       // TODO Autogenerated method stub
       super.onCreate(savedInstanceState);
       setContentView(R.layout.activity_google_maps1);
       act =this;
       gps = new GPStracker(this,act);
       
       // check if GPS enabled     
       if(gps.canGetLocation()){
            
           double latitude = gps.getLatitude();
           double longitude = gps.getLongitude();
           Log.d("lat", String.valueOf(latitude));
           Log.d("lat", String.valueOf(longitude));
           mMap = ((MapFragment) getFragmentManager()	
  				 .findFragmentById(R.id.map)).getMap();	
  	 	 //    mMap.setMapType(GoogleMap.MAP_TYPE_NORMAL);	
  	 	   //  mMap.animateCamera(	
  			//	 CameraUpdateFactory.newLatLngZoom(new LatLng(latitude,longitude), 13));	
  	 	  	
	 	 	
	 	      mMap.setMyLocationEnabled(true);	
	 	      
	 	     String PREF_FILE_NAME = "filename";
	 	    SharedPreferences sharedPreferences = getSharedPreferences(
	 	    		PREF_FILE_NAME, 0);
	 	    if(sharedPreferences.getString("SPINNER", "").equals("YES"))
	 	    {
	 	    	String id = sharedPreferences.getString("ID", "");
				new AsynctaskList(this, mMap,latitude,longitude,1,1).execute("http://api.groupon.com/v2/deals.json?client_id=dbaa2d7f2b3d92ec6b509f74f48243b58689af11&division_id="+id);

	 	    }
	 	    else{
	 	 	   new Asynctask_location(this,mMap,latitude,longitude,1).execute("http://maps.google.com/maps/api/geocode/json?latlng="+latitude+","+longitude+"&sensor=true");
	
	 	    }
	 	    
	 	   // new AsynctaskList(this, listview,mMap,latitude,longitude).execute("http://api.groupon.com/v2/deals.json?client_id=dbaa2d7f2b3d92ec6b509f74f48243b58689af11&lat="+latitude+"&lng="+longitude+"&radius=30");
            
           // \n is for new line
	 	   
	 	    //  Toast.makeText(getApplicationContext(), "Your Location address is" + finalAddress, Toast.LENGTH_LONG).show();    

	 	      //Toast.makeText(getApplicationContext(), "Your Location is - \nLat: " + latitude + "\nLong: " + longitude, Toast.LENGTH_LONG).show();    
       }else{
           // can't get location
           // GPS or Network is not enabled
           // Ask user to enable GPS/network in settings
           gps.showSettingsAlert();
          
       }
       
       handl = new Handler(new Handler.Callback() {

			@Override
			public boolean handleMessage(Message msg) {
				// TODO Auto-generated method stub
				final ArrayList<Params> res = msg.getData().getParcelableArrayList("DATA");
				Log.d("tag1", res.toString());
				mMap.clear();
				
				//.snippet(dist+ " Miles Away")
              
				for(int i=0;i<res.size();i++)
				{
					if((!(res.get(i).getRedemption_loc().equals("Online Deal")))&&
						(!(res.get(i).getRedemption_loc().equals("On Location"))))
					{
					Double distanc = AsynctaskList.distance(latitude,longitude,res.get(i).getLat(),res.get(i).getLng());
					DecimalFormat myFormatter = new DecimalFormat("00.00");
					String dist = myFormatter.format(distanc);
					
					mMap.addMarker(new MarkerOptions()	
			 	     .position(new LatLng(res.get(i).getLat(),res.get(i).getLng()))	
			 	     .title(res.get(i).getTitle())
					.snippet(dist+ " Miles Away")
	                .icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE)));
				

					}
				
			
				mMap.animateCamera(	
			   			 CameraUpdateFactory.newLatLngZoom(new LatLng(res.get(0).getLat(),res.get(0).getLng()), 9));
				
				
				mMap.setOnInfoWindowClickListener(new OnInfoWindowClickListener() {
					
					@Override
					public void onInfoWindowClick(Marker arg0) {
						// TODO Auto-generated method stub
						LatLng lt = arg0.getPosition();
						Double lat = lt.latitude; 
						Double lng = lt.longitude;
						//Toast.makeText(GoogleMaps1.this, String.valueOf(lat)+String.valueOf(lng), Toast.LENGTH_LONG).show();
						for(int i=0;i<res.size();i++)
						{ if((lat==res.get(i).getLat()) && (lng==res.get(i).getLng()))
						{ url=res.get(i).getDealurl();}}
						//Log.d("WEB",url);
						//Intent inte = new Intent(GoogleMaps1.this, WebActivity2.class);
						//inte.putExtra("LINK", url); GoogleMaps1.this.startActivity(inte);   /*Intent detail = new Intent(currentContext, DetailedActivity.class); detail.putParcelableArrayListExtra("PARCEL",ListView_Deals.getResult() ); detail.putExtra("POS", arg2); currentContext.startActivity(detail);*/ ;
					}
				});
				
			}
				return false;
			}
			});
       
       
   }

 


	@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
		// TODO Auto-generated method stub
		super.onActivityResult(requestCode, resultCode, data);
		 if (resultCode == 1) {
			 double latitude = gps.getLatitude();
	         double longitude = gps.getLongitude();
		 	   new Asynctask_location(this,mMap,latitude,longitude,1).execute("http://maps.google.com/maps/api/geocode/json?latlng="+latitude+","+longitude+"&sensor=true");

		 }
	}




	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.google_maps, menu);
		return true;
	}
	
	
	
       
	      

}